history.txt
src/frontend/terminal.rs

Adds the ability to write Clarity over multiple lines. It counts open braces and will hint the last brace type you are in. The feature makes it easier to write Clarity interactively as you are not forced to either (a) write the whole function definition in a single line, or (b) write code in a different editor and then paste it into the REPL. If you close the braces in the wrong order, it discards the input and allows you to recover (See last example).
Looks like this (every line was followed by a line-feed, notice the prompt changes):
```
clarity-repl v0.12.2
Enter "::help" for usage hints.
Connected to a transient in-memory database.
>> (+ 1 2)
3
>> (+
(.. 1
(.. 2
(.. 3
(.. )
6
>> (define-public (example)
(.. (ok true)
(.. )
→ .ST000000000000000000002AMW42H.contract-2 contract …
```

feat: multiline entry

---

.gitignore
history.txt
src/frontend/terminal.rs

Addresses #12. Super minor change.
Introduces optional env var `CLARITY_REPL_HISTORY_FILE`.
E.g.:
```bash
export CLARITY_REPL_HISTORY_FILE=~/.clarity_repl_history
clarity-repl
```

feat: set history file location using env

---

src/repl/interpreter.rs

Fixes hirosystems/clarinet#112.
The bug can be seen by minting an NFT.  Example:
```
>> (contract-call? .velocity claim)
Events emitted
{"type":"nft_mint_event","nft_mint_event":{"asset_identifier":"ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM.velocity::velocity","recipient":"ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM","value":"u1"}}
(ok u1)
>> ::get_assets_maps
+------------------------------------------------------+--------------------+-----------------+
| Address                                              | .velocity.velocity | STX             |
+------------------------------------------------------+--------------------+-----------------+
| ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM (deployer) | 1                  | 100000000000000 | …
```

fix: NFT count in ::get_assets_maps was debited, not credited

---

src/frontend/terminal.rs

This makes clarinet's console a lot more useful: load a previous session's history file if it's present.

feat: load history file on cli startup, if present

---

.github/workflows/ci.yaml
.gitignore
.husky/commit-msg
Cargo.toml
package.json
src/clarity/contexts.rs
src/clarity/costs/mod.rs
src/clarity/coverage.rs
src/clarity/mod.rs
src/clarity/util/bitcoin/blockdata/transaction.rs
src/clarity/util/bitcoin/internal_macros.rs
src/clarity/util/bitcoin/network/constants.rs
src/clarity/util/bitcoin/network/encodable.rs
src/clarity/util/retry.rs

Closes https://github.com/hirosystems/clarity-repl/issues/28
Added a CI workflow to perform the following:
* Audits and format checks
* Build the clarity-repl and wasm on PRs
* Create a GH release and git tag on the `main` branch when appropriate (following @[conventional commits](https://www.conventionalcommits.org/en/v1.0.0/#summary))
* Upload the clarity-repl WASM artifact to the GH release
* Publish the clarity-repl WASM NPM package
* Publish clarity-repl crate to creates.io
Also added a commit hook to check for commit messages which fit the conventional commit style.
No tests run for CI yet since there are none, but this step can be added once tests are merged in to `main`.

ci: automate

---

src/analysis/call_checker.rs
src/analysis/mod.rs

For example, for the following contract:
```clarity
(define-private (foo (amount uint))
(ok amount)
)
(define-public (main)
(ok (foo u1 u2))
)
```
This analysis pass will generate the error:
```
test:6:9: error: incorrect number of arguments in call to foo (expected 1 got 2)
(ok (foo u1 u2))
^~~~~~~~~~~
```
Resolves #47

feat: check argument count to user-defined funcs

---

Cargo.toml
src/bin.rs
src/clarity/database/clarity_db.rs
src/clarity/database/datastore.rs
src/repl/interpreter.rs
src/repl/session.rs

This PR improves upon the existing `Datastore` MARF emulation, enabling Clarity functions `at-block` and `get-block-info?`.
issues: #18, #20 #27

Improved MARF emulation

---

.github/workflows/open-develop-pr.yaml

Automatically merge main back into develop after a release.

ci: add workflow to open PR after release

---

src/clarity/database/datastore.rs
src/repl/session.rs

Fixes #54.
When advancing the chain tip, the datastore was not updating the `block_id_lookup` map correctly.

Fix: emulated MARF advance_chain_tip

---

src/analysis/annotation.rs
src/analysis/check_checker/mod.rs

The filter annotation allows developers to tell the check-checker to
filter one or more inputs on an expression that cannot be detected as a
filter. This is useful when a check on some unrelated inputs indirectly
validates another input. For example:
```clarity
(define-public (withdraw (amount uint))
(begin
;; #[filter(amount)]
(asserts! (is-eq tx-sender (var-get admin)) (err u400))
(stx-transfer? amount (as-contract tx-sender) tx-sender)
)
)
```
The filter annotation takes either a comma-separated list of parameter
names to filter, or a '*', which filters everything.
Resolves #72

feat: add 'filter' annotation

---

.github/workflows/ci.yaml

The GH_TOKEN secret is required for the semantic release step, but that
only runs on a PR to main. Since forks can open a PR to develop, which
needs to run the build and testing, but not the semantic release, we can
use the GITHUB_TOKEN instead. Fix from @CharlieC3.

fix: resolve CI failure for forks

---

README.md

The instructions are referring to *this repository" but pointing to another.

updated to correct repository

---

README.md

Since the default branch is `develop`, when users clone the repo, it
will be in this branch by default. This change clarifies in the README
that if they want the latest stable code, they should switch to the
`main` branch.
Resolves: #71

docs: clarify develop vs main branch

---

Cargo.toml
src/repl/interpreter.rs
src/repl/session.rs
src/repl/settings.rs

I'm working on sharing Orchestra, and this effort involves opening some PR on the REPL and Clarinet. With this PR, we're adding:
- ability to save a contract in the analysis database, without executing the contract
- update of Tokio
- iteration on `requirements`: a stable version of this feature could be very helpful in the context of Orchestra. I've been using this repo https://github.com/friedger/clarity-catamaranswaps/pull/2 for stressing this feature, and ended up fixing a bug in the dependency graph traversal + added the ability to cache on disk required contracts.

Orchestra requirements + various improvements

---

src/repl/session.rs

The output from the initial contracts got dropped with the changes for
lazy interpretation. This is just restoring that output.

fix: append output from initial contracts

---

Cargo.toml

The `reqwest` dependency was unintentionally using OpenSSL (a C library) instead of `rustls` (pure rust library). This was causing compilation issues on various platforms.
It looks like the original intent was to use `rustls` but the toml was misconfigured. 
The following config changes are required to use rustls and disable openssl:
```toml
reqwest = { default-features = false, features = ["rustls-tls"] }
```
-----
Before toml fix:
```
cargo tree -i openssl-sys            
openssl-sys v0.9.72
├── native-tls v0.2.8
│   ├── hyper-tls v0.5.0
│   │   └── reqwest v0.11.9
│   │       └── clarity-repl v0.22.1 (/Users/matt/Projects/clarity-repl)
│   ├── reqwest v0.11.9 (*)
│   └── tokio-native-tls v0.3.0
│       ├── hyper-tls v0.5.0 (*)
│       └── reqwest v0.11.9 (*)
└── openssl v0.10.38
└── …
```

fix: rustls was not properly enabled (openssl c lib was being used)

---

src/repl/ast/parser/error.rs
src/repl/ast/parser/mod.rs

In the case where a list contains another list, there was previously no
error reported if there was no space before the '(' in the list, for
example:
```clarity
(define-public (foo)
(ok(print "hello"))
)
```
This is now properly reported with the message, "expected whitespace
before expression."
Fixes #110

fix: check for whitespace between exprs in list

---

src/macros.rs
src/repl/mod.rs
src/repl/session.rs
src/repl/tracer.rs

```
>> ::trace (contract-call? .foo hello .bar)
(contract-call? .foo hello .bar)  <console>
├── ( add 4 2 )  foo:23:19
│   │ ↳ args: 4 2
│   └── 6
├── ( add 3 ( add 4 2 ) )  foo:23:12
│   │ ↳ args: 3 6
│   └── 9
├── ( set-my-var 7 )  foo:24:12
│   │ ↳ args: 7
│   └── true
├── ( contract-call? ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM.bar do-something ( var-get myVar ) )  foo:25:14
│   │ ↳ args: 7
│   ├── ( max10 val )  bar:19:24
│   │   │ ↳ args: 7
│   │   └── 7
│   └── (ok 0)
├── ( contract-call? b do-something 42 )  foo:26:5
│   │ ↳ callee: ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM.bar
│   │ ↳ args: 42
│   ├── ( max10 val )  bar:19:24
│   │   │ ↳ args: 42
│   │   └── 10
│   └── (ok 7)
└── (ok 7)
Events emitted
{"type":"contract_event","contract_event":{"contract_identifier":"ST1PQHQKV0RJ …
```

Add an execution tracer to the REPL

---

src/analysis/ast_dependency_detector.rs

Since the `ASTDependencyDetector` is now used before any checks have
been performed on the AST, it cannot make assumptions about correctness
and crash when that assumption is wrong. For example, when unwrapping an
expected type, we also provide a default value in case the type was
incorrect in the AST.

fix: make dep detector robust to invalid ASTs

---

src/analysis/ast_visitor.rs
src/repl/ast/parser/error.rs
src/repl/session.rs

Since the AST may be invalid, retrieving args from a list is not safe, since we cannot guarantee that the correct argument count is present. This commit adds a default value to fall back on so that the analysis may continue without crashing.
Fixes: #173

fix: harden `ASTVisitor` with default args

---

src/frontend/terminal.rs

This fixes an interactive clarinet bug, and allows for pasting multiple
lines into the console.  I've tested it lightly by copying/pasting
several lines from another window into clarinet console.
There are a couple of changes in behavior.
* The console echos back the form before its result:
>> (concat "a " " b") (concat "r" "d")
;; (concat "a " " b")
"a  b"
;; (concat "r" "d")
"rd"
>>
* Multiple expressions on the same line end up as separate entries
in the history.  Pressing the up arrow after the above input
brings up only the second form, not both of them.  This might not
be desirable.
* This also works, though i'm not sure if it should:
(concat "a " " b")(concat "r" "d")
Without my change, this results in
>> (concat "a " " b")(concat "r" "d")
error: Expected whitespace or a close …

feat: allow pasting of multiple lines

---

src/analysis/ast_dependency_detector.rs

Instead of reporting an error in `order_contracts` when a contract is
not found, we now just skip that dependency. Reporting an error at that
point is not useful, because a better error with proper location
information can be reported by the later analysis.
See hirosystems/clarinet#396

fix: remove unhelpful dependency error

---

src/analysis/ast_dependency_detector.rs

The `__transient` contract is used as a placeholder when the principal
is invalid, so just ignore this in the dependency detector, and a proper
error will be generated for it.

fix: don't create a dependency for `__transient`

---

Cargo.lock
components/chainhook-cli/src/cli/mod.rs
components/chainhook-cli/src/scan/bitcoin.rs
components/chainhook-event-observer/Cargo.toml
components/chainhook-event-observer/src/hord/db/mod.rs
components/chainhook-event-observer/src/hord/inscription.rs
components/chainhook-event-observer/src/hord/mod.rs
components/chainhook-event-observer/src/indexer/bitcoin/mod.rs
components/chainhook-event-observer/src/observer/mod.rs
components/chainhook-types-rs/src/rosetta.rs

We are test driving the concept of [cursed inscriptions](https://github.com/casey/ord/issues/2045). This will probably take multiple iteration. 
With this PR, our goal is to create cursed inscription for transactions that tried to inscribe satoshis, using other inputs than input #0.

feat: attempt to support cursed inscriptions

---

components/client/typescript/package-lock.json
components/client/typescript/package.json
components/client/typescript/src/schemas/bitcoin/payload.ts
components/client/typescript/src/server.ts

* Send HTTP 500 response on payload errors so node can retry
* Fix `curse_type` schema to include null and tagged objects
* Add `wait_for_chainhook_node` option to be able to skip server pings on local chainhook tests

feat: upgrade typescript client

---

Cargo.lock
components/chainhook-cli/Cargo.toml
components/chainhook-sdk/Cargo.toml

Fixes #310 
This PR updates some dependencies to get the new `clarinet-files` version working. I've also pinned all stacks/hiro dependencies so we can update manually and ensure everything is working so this doesn't happen again.

fix: update/pin dependencies

---

components/client/typescript/package-lock.json
components/client/typescript/package.json
components/client/typescript/src/schemas/bitcoin/payload.ts
components/client/typescript/src/schemas/payload.ts
components/client/typescript/src/server.ts

* Remove `inscription_number` and `ordinal_number` from inscription transfers
* Add option to validate chainhook payload schemas
* Add option to set a custom body size limit

feat: update inscription transfer schemas

---

Cargo.lock
components/chainhook-cli/Cargo.toml

The project couldn't build because `chainhook-cli` was pointing to an outdated version of `chainhook-sdk`. This PR fixes it.

fix: update chainhook-sdk

---

docs/how-to-guides/how-to-run-chainhook-as-a-service-using-bitcoind.md
docs/how-to-guides/how-to-run-chainhook-as-a-service-using-stacks.md
docs/how-to-guides/how-to-use-chainhooks-with-bitcoin.md

Chainhook docs: Fixed note and tip formats

---

docs/how-to-guides/how-to-run-chainhook-as-a-service-using-bitcoind.md

The ["Run Chainhook as a Service using Bitcoind"](https://docs.hiro.so/chainhook/how-to-guides/how-to-run-chainhook-as-a-service-using-bitcoind) guide was revamped in advance of Chainhooks general launch.
N/A
N/A

Updated "chainhooks service with bitcoind" How To doc

---

Cargo.lock
components/chainhook-cli/Cargo.toml
components/chainhook-cli/src/scan/bitcoin.rs
components/chainhook-cli/src/scan/stacks.rs
components/chainhook-cli/src/service/runloops.rs
components/chainhook-sdk/Cargo.toml
components/chainhook-sdk/src/chainhooks/bitcoin/mod.rs
components/chainhook-sdk/src/chainhooks/tests/mod.rs
components/chainhook-sdk/src/indexer/tests/helpers/stacks_shapes.rs
components/chainhook-sdk/src/utils/mod.rs
components/chainhook-types-rs/Cargo.toml
components/chainhook-types-rs/src/rosetta.rs
components/client/typescript/src/schemas/bitcoin/payload.ts

- Bump retries counts for initial scans
- Introduce new ordinals curse type wildcard
- Simplify ordinals schemas by removing curse variants
- Bump versions
- Cargo format

Quick tweaks

---

Cargo.lock
components/chainhook-cli/src/cli/mod.rs
components/chainhook-cli/src/service/tests/mod.rs
components/chainhook-sdk/Cargo.toml
components/chainhook-sdk/src/chainhooks/stacks/mod.rs
components/chainhook-sdk/src/chainhooks/tests/mod.rs
components/chainhook-sdk/src/chainhooks/types.rs
docs/chainhook-openapi.json

This PR introduces the ability to match on a `print_event`'s values with a regex string rather than just with the previous `contains` field.
Fixes #348 
This allows the following new `if_this` condition for a stacks predicate:
```JSON
{
"scope": "print_event",
"contract_identifier": "ST3AXH4EBHD63FCFPTZ8GR29TNTVWDYPGY0KDY5E5.loan-data",
"regex": "... some regex to match on the event data"
}
```
---

feat: allow matching with regex for stacks print_event

---

docs/how-to-guides/how-to-run-chainhook-as-a-service-using-bitcoind.md
docs/how-to-guides/how-to-run-chainhook-as-a-service-using-stacks.md

@mefrem: Fixed a pathname error in docs, fixed a typo, and added some clarifying language to other sections.
- Fixed `bitcoind` and `bitcoin.conf` pathnames
- Removed double words "predicates" 
- Clarified bitcoind node setup instructions
@ryanwaits to add changes/comments to the "Run Chainhook as a Service using Stacks" How To guide

docs: update chainhook guides

---

components/chainhook-cli/src/scan/bitcoin.rs

When scanning the chain `chainhook predicates scan` setting a `start_block` predicate param, blockchain tip is not evaluated. I don't know if this was intended (leaving tip unscanned) but it's misleading to skip the tip.
Unlikely

fix: retrieve blocks until tip

---

components/chainhook-cli/src/service/mod.rs

Previously, a serialized `PredicateStatus` would have the format:
```JSON
{ "scanning": { "last_evaluated_block": ... }
```
where the predicate status type is the key that points to the data. This PR changes this format to be:
```JSON
{
"type": "scanning",
"info": { "last_evaluated_block": ... }
}
```

chore: update predicate status format for easier parsing

---

components/chainhook-sdk/src/chainhooks/bitcoin/mod.rs
components/chainhook-sdk/src/chainhooks/bitcoin/tests.rs
docs/how-to-guides/how-to-use-chainhooks-with-bitcoin.md

Handles OP_RETURN  predicates correctly.
Potentially yes, but unlikely.
Currently there is a OP_RETURN handler, that matches the `output.script_pubkey` against the expression set in the predicate, although this implementation does not confirm with the documentation, someone might be relying on it
fixes #385 #388

fix: op_return predicate evaluation

---

components/chainhook-cli/src/scan/bitcoin.rs
components/chainhook-cli/src/scan/stacks.rs
components/chainhook-cli/src/service/mod.rs
components/chainhook-cli/src/service/tests/mod.rs

Previously, when the unconfirmed predicate status was set after the status originally was scanning, we were adding the number of evaluated blocks with the previous statuses number of blocks. When scanning, we have a running total of blocks scanned, so we don't need to use the previously stored data.
---

fix: correctly calculate evaluations for predicate status

---

components/chainhook-cli/src/service/mod.rs
components/chainhook-cli/src/service/tests/mod.rs

This changes the predicate status timestamps:
- from String (converted from a u128) to a u64
- this means we are now storing the data in seconds rather than milliseconds
- makes them optional (so they will not appear in a serialized status if set to `None`)
Previously the timestamp was in milliseconds, now it's in seconds. Anyone depending on the timestamp being in milliseconds could be impacted by this change.
---

fix: make predicate status timestamps optional

---

.github/workflows/ci.yaml

changes to the CI workflow.
adding auto deployments using docker container digest to the k8s repo.
dev and stg will auto approve, while prod will require manual approval

ci: update CD process

---

components/chainhook-sdk/src/chainhooks/stacks/mod.rs
components/chainhook-sdk/src/chainhooks/tests/mod.rs
components/chainhook-sdk/src/chainhooks/types.rs

The new field `include_contract_abi` already was optional for the user-facing type `StacksChainhookNetworkSpecification`, but was not optional for the internal type `StacksChainhookSpecification`. Any time we converted to a `StacksChainhookSpecification`, we'd `.unwrap_or(false)`, which seemed okay.
However, a running Chainhook node has the `StacksChainhookSpecification` type saved in redis, so whenever a pre-existing node is restarted after upgrading, it is missing the required `include_contract_abi` field and errors.
This PR makes the field optional everywhere.
I'll need to think about how to add tests to prevent this sort of bug in the future.

fix: make `include_contract_abi` optional

---

components/chainhook-cli/src/service/mod.rs
components/chainhook-sdk/src/indexer/stacks/mod.rs

This PR is fixing the management of the redis connection. In the current approach, we're reusing an existing connection that is being opened at startup for test purposes, but that can get broken after some time if blocks take time to arrive.
Fix: we open/close a new connection every time a new block hits the API.

fix: redis conn

---

components/chainhook-sdk/src/indexer/stacks/mod.rs

I was attempting to update Clarinet to the latest version of chainhook-sdk/types, and I ran into this issue when testing the devnet.
The devnet mines 100 bitcoin blocks, and the default `pox_info.first_burnchain_block_height` is also 100, so devnet startup would always fail.

fix(stacks-indexer): prevent subtract with overflow

---

components/chainhook-cli/src/archive/mod.rs
components/chainhook-cli/src/service/http_api.rs

Fixes #401 
Previously, memory usage peaked at 32 GB. Now, I didn't see it go above 8 MB

fix: buffer decoding of archive file to reduce memory usage

---

components/client/typescript/package-lock.json
components/client/typescript/package.json
components/client/typescript/src/server.ts

Updates the TypeScript client URLs so they match with ordhook or chainhook requirements.

fix: update ordhook URLs on typescript client

---

components/chainhook-cli/src/archive/mod.rs
components/chainhook-cli/src/scan/stacks.rs
components/chainhook-cli/src/storage/mod.rs

Previously, when parsing and archive tsv to determine the canonical fork, we would always start at block 0, even if there was a rocksdb instance containing stacks chaindata. The entire fork was loaded in memory and inserted.
Now, we start at the latest confirmed chaintip for this process, which greatly reduces the memory footprint on subsequent startups of the Chainhook service. Note: an initial run of the Chainhook service can still use significant memory.

fix: reduce memory usage in archive file ingestion 

---

.cargo/config
components/chainhook-cli/Cargo.toml

Previously, the `cargo chainhook-install` script was installing the sdk version of Chainhook, which logged data in a non-user-friendly way. This changes our features some and updates the install script to fix those logs.

fix: use cli feature for `cargo chainhook-install`

---

components/chainhook-sdk/src/chainhooks/stacks/mod.rs
components/chainhook-sdk/src/chainhooks/tests/mod.rs

When evaluatin a stacks predicate of type `ft_event` or `nft_event`, we were returning from a loop of all events after the first loop. We should only return early if there is a match, and should continue searching all events if there isn't. This PR implements that fix.
Fixes #469
---

fix: remove early return for event evaluation

---

components/chainhook-cli/src/service/mod.rs

This error caused chainhook to crash today. This route can happen if a predicate is completed, but we're still waiting on block confirmations for fully expire the predicate, and then the user deletes the predicate.

fix: remove unreachable panic; return instead

---

components/chainhook-cli/src/scan/bitcoin.rs
components/chainhook-cli/src/scan/common.rs
components/chainhook-cli/src/scan/mod.rs
components/chainhook-cli/src/scan/stacks.rs
components/chainhook-cli/src/scan/tests/mod.rs
components/chainhook-cli/src/service/mod.rs
components/chainhook-cli/src/service/runloops.rs
components/chainhook-cli/src/service/tests/mod.rs
components/chainhook-sdk/src/chainhooks/types.rs
components/chainhook-sdk/src/observer/http.rs
components/chainhook-sdk/src/utils/mod.rs

Previously, the scanning threads had some validation for the `start_block` and `end_block` that was incorrect. This PR introduces validation that does the following:
- We now allow `start_block` to be omitted by the user and we default to 0
- If there are no blocks in the database, we abort the scan and go to streaming mode rather than erroring (fixes #477)
- If the user provides an `end_block`, we validate that it is greater than the `start_block`
- If the `start_block` is greater than chain tip, we abort the scan and go to streaming mode rather than erroring (fixes #464)
This PR also adds some validation to the `BlockHeights` class. Previously, it was possible to overload the `BlockHeights::BlockRange(start_block, end_block)` function to allocate a lot of memory into an empty array. We …

fix: validate predicate `start_block` and `end_block`

---

Cargo.lock
components/chainhook-cli/src/cli/mod.rs
components/chainhook-cli/src/config/file.rs
components/chainhook-cli/src/config/generator.rs
components/chainhook-cli/src/config/mod.rs
components/chainhook-cli/src/config/tests/mod.rs
components/chainhook-cli/src/service/tests/helpers/mock_service.rs
components/chainhook-cli/src/service/tests/mod.rs
components/chainhook-cli/src/service/tests/observer_tests.rs
components/chainhook-sdk/Cargo.toml
components/chainhook-sdk/src/lib.rs
components/chainhook-sdk/src/monitoring.rs
components/chainhook-sdk/src/observer/http.rs
components/chainhook-sdk/src/observer/mod.rs
components/chainhook-sdk/src/observer/tests/mod.rs

To enable improved alerts on downtime for Hiro's hosted Chainhook service, we need Chainhook to provide metrics that can be ingested by Prometheus. This PR changes some how we track our metrics (that are served over the `/ping` endpoint of the observer) to enable Prometheus compatibility, and adds a flag to optionally start a server to supply metrics to a Prometheus client.
Starting chainhook with the `--prometheus-port XXXX` flag now enables a service that can supply Prometheus metrics at `localhost:XXXX/metrics`.
If using a config file, this option can be specified via:
```yaml
[monitoring]
prometheus_monitoring_port = XXXX
```
Chainhook will behave as usual with this flag ommitted - metrics can still be retrieved via the observer's `/ping` endpoint, but they will not be formatted for …

feat: optionally serve Prometheus metrics

---

components/chainhook-cli/src/service/tests/helpers/mock_stacks_node.rs
components/chainhook-sdk/src/chainhooks/stacks/mod.rs
components/chainhook-sdk/src/chainhooks/tests/fixtures/mod.rs
components/chainhook-sdk/src/chainhooks/tests/fixtures/stacks/testnet/occurrence.json
components/chainhook-sdk/src/chainhooks/tests/mod.rs
components/chainhook-sdk/src/indexer/stacks/mod.rs
components/chainhook-sdk/src/indexer/stacks/tests.rs
components/chainhook-sdk/src/indexer/tests/helpers/stacks_events.rs
components/chainhook-types-rs/src/events.rs

(this PR is just cherry-picking the relevant commits from @janniks in PR #417, which I apparently mucked up with some bad merging)
- closes #387 
- adds a position struct to the event and renames the event to payload (with enum type)
- updates occurences.json to include the expected serialized position for testing
---
**Note**: Any users running a Chainhook node (i.e. `chainhook service start ...`) will not have transaction event positions stored in the database, so all event position will have a value of:
``` JSON
"position": {
"index": 0
}
```
To rebuild the database with this data filled in:
- Upgrade to the latest version of Chainhook
- Delete the `stacks.rocksdb` folder inside the `working_dir` set in your `Chainhook.toml`
- Rerun Chainhook
This will rebuild your Stacks database from …

fix: add event index to transaction events

---

components/chainhook-sdk/src/chainhooks/types.rs
components/chainhook-sdk/src/indexer/bitcoin/mod.rs

fix: correctly determine PoX vs PoB block commitments

---

components/chainhook-sdk/src/observer/mod.rs

Chainhook's `chainhook_stx_highest_block_ingested` and `chainhook_btc_highest_block_ingested` metrics were not being updated on a reorg. This was causing the Chainhook node to appear to be lagging behing the source chains, event though Chainhook's reorg handler was functioning properly.
This PR sets the highest block ingested metrics on a reorg based on the highest index block being applied in the reorg.

fix(metrics): update latest ingested block on reorg

---

components/chainhook-cli/src/cli/mod.rs
components/chainhook-cli/src/service/mod.rs
components/chainhook-cli/src/service/tests/helpers/mock_service.rs
components/chainhook-cli/src/service/tests/helpers/mock_stacks_node.rs
components/chainhook-cli/src/service/tests/helpers/mod.rs
components/chainhook-cli/src/service/tests/mod.rs
components/chainhook-cli/src/service/tests/observer_tests.rs
components/chainhook-cli/src/storage/mod.rs
components/chainhook-sdk/src/indexer/mod.rs
components/chainhook-sdk/src/indexer/stacks/blocks_pool.rs
components/chainhook-sdk/src/indexer/stacks/tests.rs
components/chainhook-sdk/src/indexer/tests/helpers/stacks_shapes.rs
components/chainhook-sdk/src/indexer/tests/mod.rs
components/chainhook-sdk/src/observer/mod.rs

If Chainhook restarts in the middle of a reorg taking place, it doesn't have any context for choosing the canonical fork. Then when block collisions take place, Chainhook fails to process the new blocks, causing gaps in the blocks Chainhook has available for evaluation.
This PR seeds the stacks block indexer with unconfirmed blocks on startup, so that Chainhook has the necessary context to handle a reorg.
Most of the PR is to add two tests:
- I've added some new functionality to our very thorough indexer tests
- In addition to providing the blocks to be mined and the order to mine them, we also now allow providing some "unconfirmed" blocks to seed the block pool with.
- I've added some test cases that reproduce what caused outages on the Platform's Chainhook node
- I've added a new …

fix: seed forking handler with unconfirmed blocks to improve startup stability

---

components/chainhook-cli/src/scan/stacks.rs

The database consolidation loop doesn't need to happen if there is no new data. 
@lgalabru I'm interested in your thoughts on this. Potentially someone could break their stacks.rocksdb, then Chainhook wouldn't automatically fix it unless they deleted their archive to force a redownload, or a new archive becomes available.
I think the tradeoff is worth it because of the improvements to startup time if users are repeatedly running `chainhook predicates scan`, or if the service goes down and needs to restart.

fix: skip db consolidation if no new dataset was downloaded

---

components/chainhook-cli/src/cli/mod.rs

Previously, when using the `chainhook predicates scan` command, Chainhook would download a very large archive file to use as a data source for the scan **every time the command was run**.
The Chainhook service (`chainhook service start`), however, implements rocksdb to allow storing this dataset locally. 
This PR uses the rocksdb that a user may have created locally to improve performance of the `chainhook predicates scan` command. If a rocksdb doesn't exist or can't be created, Chainhook will fallback to the original method of downloading the archive.
Combined with #513, this PR reduces a simple scan of a few blocks from ~20 minutes to .02 seconds.
Fixes #485

feat: use stacks.rocksdb for predicate scan

---

components/chainhook-sdk/src/indexer/bitcoin/mod.rs

Before this PR, Chainhook would loop infinitely if there is a problem downloading a BTC block, and it wouldn't log much information as to what was causing the failure. This PR implements better logging, and breaks out of the loop at 10 failed attempts.

fix: log errors on block download failure; implement max retries

---

components/chainhook-cli/src/archive/mod.rs
components/chainhook-cli/src/archive/tests/mod.rs
components/chainhook-cli/src/cli/mod.rs
components/chainhook-cli/src/config/mod.rs
components/chainhook-cli/src/config/tests/mod.rs
components/chainhook-cli/src/scan/bitcoin.rs
components/chainhook-cli/src/scan/stacks.rs
components/chainhook-cli/src/service/http_api.rs
components/chainhook-cli/src/service/mod.rs
components/chainhook-cli/src/service/runloops.rs
components/chainhook-cli/src/storage/mod.rs
components/chainhook-sdk/Cargo.toml
components/chainhook-sdk/src/indexer/fork_scratch_pad.rs
components/chainhook-sdk/src/indexer/mod.rs
components/chainhook-sdk/src/indexer/stacks/mod.rs
components/chainhook-sdk/src/observer/http.rs
components/chainhook-sdk/src/observer/mod.rs
components/chainhook-sdk/src/observer/tests/mod.rs
components/chainhook-sdk/src/utils/mod.rs

This PR introduces a few fixes in an effort to improve reliability and debugging problems when running Chainhook as a service:
- Revisits log levels throughout the tool (fixes #498, fixes #521). The general approach for the logs were:
- `crit` - fatal errors that will crash mission critical component of Chainhook. In these cases, Chainhook should automatically kill all main threads (not individual scanning threads, which is tracked by #404) to crash the service.
- `erro` - something went wrong the could lead to a critical error, or that could impact all users
- `warn` - something went wrong that could impact an end user (usually due to user error)
- `info` - control flow logging and updates on the state of _all_ registered predicates
- `debug` - updates on the state of _a_ predicate
- …

fix: improve error handling, and more!

---

Cargo.lock
components/chainhook-cli/Cargo.toml
components/chainhook-sdk/Cargo.toml
components/chainhook-sdk/src/chainhooks/stacks/mod.rs
components/chainhook-sdk/src/indexer/stacks/mod.rs
components/chainhook-sdk/src/observer/mod.rs
components/chainhook-types-js/src/index.ts
components/chainhook-types-rs/src/rosetta.rs
components/client/typescript/src/schemas/stacks/tx_kind.ts
dockerfiles/components/chainhook-node.dockerfile

chore: update clarinet and clarity-vm

---

Cargo.lock
Cargo.toml
components/chainhook-sdk/Cargo.toml
components/chainhook-sdk/src/chainhooks/stacks/mod.rs
components/chainhook-sdk/src/indexer/mod.rs
components/chainhook-sdk/src/indexer/stacks/mod.rs
components/chainhook-sdk/src/lib.rs
components/chainhook-sdk/src/observer/http.rs

- replace the stacks-rpc-client dependency in favor of stacks-codec one
- replace `stacks_rpc_client::PoxInfo` with a new `PoxConfig` struct
- I think that PoxInfo was misused here, it's supposed to represent the live state of pox on the chain, while chainhook-sdk is just storing some default config values

chore: use stacks-codec

---

components/chainhook-cli/src/service/mod.rs

Every 32 stacks blocks, Chainhook attempts to check for a new archive file to fix any potential holes in the database. This process requires readwrite access to the stacks.rocksdb. However, the process that called this subprocess already had a readwrite instance of the database open, which was preventing the lock from being cleared.
This PR sets the scope of the initial usage of the db in order to free up the lock.

fix: limit scope of stacks_rw_db usage to free lock

---

components/chainhook-sdk/src/indexer/fork_scratch_pad.rs
components/chainhook-sdk/src/indexer/mod.rs
components/chainhook-sdk/src/indexer/stacks/blocks_pool.rs
components/chainhook-sdk/src/monitoring.rs
components/chainhook-sdk/src/observer/http.rs
components/chainhook-sdk/src/observer/mod.rs
components/chainhook-sdk/src/observer/tests/mod.rs

fix: correctly track bitcoin block append metrics; add additional metrics

---

components/chainhook-sdk/src/chainhooks/bitcoin/mod.rs
components/chainhook-sdk/src/chainhooks/bitcoin/tests.rs
components/chainhook-sdk/src/observer/mod.rs

When a Chainhook is triggered and we send a payload to a user, we filter some values based on user settings (`include_proof`, `include_inputs`, etc). This helps to reduce the payload size that is sent over the wire.
However, when we created this payload, we were omitting these fields completely even though the corresponding type does not have those fields as optional. This makes using our SDK types for deserialization impossible.
This PR adds in those fields in all cases and sets them to empty values if filtered out.

fix: make bitcoin payload serialization deserializable

---

components/chainhook-sdk/src/indexer/bitcoin/mod.rs
components/chainhook-sdk/src/observer/http.rs

fix: shut down observer on bitcoin block download failure

---

components/chainhook-cli/src/scan/stacks.rs
components/chainhook-cli/src/service/mod.rs
components/chainhook-cli/src/service/runloops.rs
components/chainhook-sdk/src/chainhooks/stacks/mod.rs
components/chainhook-sdk/src/observer/mod.rs

fix: set `Interrupted` status for streaming predicates that fail

---

components/chainhook-cli/src/cli/mod.rs

Previously, these were output as `CRIT` errors, but they should just be printed to the console.

fix: print to console for unknown cli commands

---

components/chainhook-cli/src/scan/bitcoin.rs
components/chainhook-cli/src/scan/stacks.rs

The predicate status is used to report data to users and to pick back up where the service left off on a restart. This change updates the scanning predicate status to be updated on every successful trigger of a scanning predicate, to be sure we don't scan blocks twice on a restart (if the status was set to a previous block, we'd start on that block at startup)

chore: update predicate scanning status on every trigger

---

components/chainhook-cli/src/cli/mod.rs
components/chainhook-cli/src/scan/bitcoin.rs
components/chainhook-cli/src/scan/common.rs
components/chainhook-cli/src/scan/stacks.rs
components/chainhook-cli/src/service/mod.rs
components/chainhook-cli/src/service/runloops.rs
components/chainhook-cli/src/service/tests/mod.rs
components/chainhook-cli/src/service/tests/runloop_tests.rs
components/chainhook-sdk/src/observer/mod.rs
components/chainhook-sdk/src/observer/tests/mod.rs
components/chainhook-types-rs/src/lib.rs

Previously, when Chainhook was run as a service and the runloop to scan stacks/bitcoin predicates was set, we had no way to abort that scan. If a predicate was set to scan 1m blocks, but the user discovered the predicate was wrong and needed to delete, the user could delete the predicate from the store, but the scan thread had already started and would run until completion.
This PR adds an abort signal to an ongoing scan so that when a predicate is deregistered, the scan is canceled.

fix: allow aborting a predicate scan

---

Cargo.lock

This PR removes about 100 dependencies from the Cargo.lock.
This is a follow up of this PR https://github.com/stacks-network/stacks-core/pull/4969 (see the details regarding the new cargo feature and the useless clarity-wasm features in this context).
It improves the build speed buy about 25% (with no cache, on my machine)

chore: update cargo lock to use the latest clarity-vm version removing lots of dependencies

---

Cargo.lock
components/chainhook-cli/Cargo.toml
components/chainhook-sdk/Cargo.toml

This PR update to the latest reqwest and tokio versions
I'm doing some maintenance in clarinet dependencies. Trying to remove some older version especially when we already import newer ones (we have a lot of dependencies with multiple versions imported).
This PR is a step in this direction. It's not a one-shot PR but instead an attempt to start having a better dependencies version management in our projects
Such changes can always result in side effects hard to anticipate. But the unit tests are here to prevent that.
Let me know if more testing should be done.

chore: upgrade tokio and reqwest dependencies

---

Cargo.lock
components/chainhook-sdk/Cargo.toml
components/chainhook-sdk/src/chainhooks/stacks/mod.rs
components/chainhook-sdk/src/indexer/stacks/mod.rs

I'm willing to remove this pattern from stacks-codec and clarity repl
https://github.com/hirosystems/clarinet/blob/ce1ffeaaf645de2d9a581d1d727e660cacb1e288/components/stacks-codec/src/lib.rs#L6-L10
```rust
pub mod clarity {
#![allow(ambiguous_glob_reexports)]
pub use ::clarity::types::*;
pub use ::clarity::vm::*;
pub use ::clarity::*;
}
```
It's error prone, adds complexity, for no value in this context. It's easier for packages to simply rely on the clarity crates (that will soon™ be imported from crates.io)

refactor: use clarity crate

---

components/chainhook-cli/src/cli/mod.rs
components/chainhook-cli/src/scan/stacks.rs

This PR changes the way chainhook imports a Stacks node TSV into rocksdb.
Before, it loaded the entire canonical chinstate (including the full block JSON messages) onto a `VecDeque` in memory and then drained that data into rocksdb. This was a very memory intensive process which crashed our dev pods ever time it ran.
Now, the process was changed to a `VecDeque` that only keeps the line numbers of the TSV where the block data exists, so it can later read blocks from the file 1 by 1 and insert them into rocksdb.

fix: optimize memory for stacks tsv import into rocksdb

---

components/client/typescript/src/predicates.ts
components/client/typescript/tests/predicates.test.ts

Replaces the sync `node:fs` operations with async `node:fs/promises` async operations. This fixes potential issues with the main program loop completely blocking while waiting on disk operations. E.g. sync disk operations causing lots of small pauses/delays while serving http requests.

Fix: async fs operations
