hirosystems/chainhook

src/clarity/codec/transaction.rs
src/repl/interpreter.rs
src/repl/mod.rs
src/repl/session.rs

Add encode/decode commands to REPL

---

.github/workflows/ci.yaml
src/bin.rs
src/lib.rs

set `costs_version` config option

fix: set costs_version

---

.github/workflows/ci.yaml
CHANGELOG.md
Cargo.toml

After this is merged, I will open another PR to automate this for the next release (thanks @CharlieC3).

Merge main back into develop

---

src/clarity/docs/mod.rs

Address https://github.com/hirosystems/clarity-lsp/issues/49

fix: nft-burn snippet

---

src/analysis/check_checker/mod.rs

This changeset allows a user-defined private function to act as a filter
in the caller -- meaning that tainted data passed into the function can
be treated as filtered after the call. This is a common usage pattern
and should remove many false positive warnings in real smart contracts.

feat(check-checker): allow private function filter

---

src/analysis/ast_visitor.rs
src/analysis/check_checker/mod.rs

Fix contract-of traversal

---

src/analysis/call_checker.rs

The type-checker in the clarity library checks for the case where there
are too few arguments, but not too many. This may be fixed in the
type-checker in 2.1 (because it is consensus breaking, see
stacks-network/stacks-blockchain#3018), but for now, we can do this in
the REPL.
Resolves: hirosystems/clarinet#228

fix: add checks for argument counts to map-* funcs

---

src/analysis/check_checker/mod.rs

Operations on the sender's own wallet are considered safe, but this
is not correct if the operation is inside of an `as-contract`.

fix: consider as-contract in check-checker

---

src/analysis/call_checker.rs
src/analysis/check_checker/mod.rs
src/analysis/dependency_detector.rs
src/clarity/callables.rs
src/clarity/contexts.rs
src/clarity/debug.rs
src/clarity/mod.rs
src/frontend/terminal.rs
src/repl/interpreter.rs
src/repl/session.rs

Debugger supports source, function, and data breakpoints, and step-in, step-out, and step-over execution to debug smart contracts.

Add debugger support

---

src/repl/session.rs

Reloads the existing contract(s) in the session, as per https://github.com/hirosystems/clarity-repl/issues/15#issuecomment-1086829948.

feat: add reload command

---

src/repl/interpreter.rs

fix: update block limits to 2.05 numbers

---

src/clarity/debug/dap/mod.rs

The debugger was not working on Windows and I discovered that it was due
to different formatting of the paths. This commit switches from storing
a `String` to storing a `PathBuf` which can be compared correctly.

fix: resolve problem comparing paths in Windows

---

Cargo.toml
src/analysis/ast_dependency_detector.rs
src/clarity/coverage.rs
src/clarity/diagnostic.rs
src/frontend/terminal.rs
src/lib.rs
src/repl/mod.rs
src/repl/session.rs
src/repl/settings.rs

With this PR, we are getting rid of the requirements, we came to the conclusion that a more natural place would be clarinet.
There a few other adjustments / additions / fixes that were made along the way of working on https://github.com/hirosystems/clarinet/pull/333, that are required and expected by this PR.

Removing requirements / links features from the REPL

---

src/analysis/ast_dependency_detector.rs

fix: fix crash on contract-call to invalid func

---

src/repl/session.rs

Adds the `::read` command to the console.

Read expressions from a file

---

components/chainhook-cli/Cargo.toml
components/chainhook-cli/src/cli/mod.rs
components/chainhook-cli/src/config/generator.rs
components/chainhook-cli/src/config/mod.rs
components/chainhook-cli/src/main.rs
components/chainhook-cli/src/node/mod.rs
components/chainhook-cli/src/scan/bitcoin.rs
components/chainhook-cli/src/scan/stacks.rs
components/chainhook-event-observer/src/chainhooks/bitcoin/mod.rs
components/chainhook-event-observer/src/chainhooks/stacks/mod.rs
components/chainhook-event-observer/src/chainhooks/types.rs
components/chainhook-event-observer/src/observer/mod.rs
components/chainhook-event-observer/src/utils/mod.rs

PR addressing https://github.com/hirosystems/chainhook/issues/211 and some other issues.

Close the loop on scans, better errors

---

components/chainhook-cli/src/scan/stacks.rs
components/chainhook-event-observer/src/chainhooks/stacks/mod.rs

Address https://github.com/hirosystems/chainhook/issues/210

fix: deployer predicate wildcard

---

docs/faq.md
docs/how-to-guides/how-to-run-chainhook-as-a-service.md
docs/how-to-guides/how-to-use-chainhook-with-bitcoin.md
docs/how-to-guides/how-to-use-chainhook-with-stacks.md

- Fixed title cases
- FAQ's formatting

Fixed minor formatting issues

---

docs/overview.md

Update overview title from Overview to "Chainhooks Overview"

Update title for overview

---

Cargo.lock
README.md
components/chainhook-cli/Cargo.toml
components/chainhook-cli/src/archive/mod.rs
components/chainhook-cli/src/cli/mod.rs
components/chainhook-cli/src/scan/bitcoin.rs
components/chainhook-cli/src/service/mod.rs
components/chainhook-sdk/Cargo.toml
components/chainhook-sdk/src/chainhooks/bitcoin/mod.rs
components/chainhook-sdk/src/hord/db/mod.rs
components/chainhook-sdk/src/hord/mod.rs
components/chainhook-sdk/src/indexer/bitcoin/mod.rs
components/chainhook-sdk/src/observer/mod.rs
components/chainhook-types-rs/Cargo.toml
components/chainhook-types-rs/src/bitcoin.rs
components/chainhook-types-rs/src/lib.rs
components/chainhook-types-rs/src/processors.rs
components/chainhook-types-rs/src/rosetta.rs

With this PR, we're stabilizing and fixing many glitches / issues that have been experienced in our different environments (dev/stg/prd).

fix: myriad of adjustments

---

components/chainhook-cli/src/service/mod.rs
components/chainhook-sdk/Cargo.toml
components/chainhook-sdk/src/observer/http.rs
components/chainhook-sdk/src/observer/mod.rs
components/chainhook-sdk/src/observer/tests/mod.rs

feat: add metrics to `/ping` response of event observer server

---

components/chainhook-cli/src/service/http_api.rs

fix: add more details to 422 errors for `POST /v1/chainhooks` route

---

docs/faq.md
docs/getting-started.md
docs/how-to-guides/how-to-run-chainhook-as-a-service-using-bitcoind.md
docs/how-to-guides/how-to-run-chainhook-as-a-service-using-stacks.md
docs/how-to-guides/how-to-use-chainhook-with-bitcoin.md
docs/how-to-guides/how-to-use-chainhook-with-stacks.md
docs/overview.md

Fixed broken links and grammar.

Fixed broken links and grammar issues

---

docs/getting-started.md
docs/how-to-guides/how-to-run-chainhook-as-a-service-using-bitcoind.md
docs/how-to-guides/how-to-run-chainhook-as-a-service-using-stacks.md
docs/how-to-guides/how-to-use-chainhook-with-bitcoin.md
docs/overview.md

Changed absolute links to relative links to fix the build issues.

Changed links to use relative links

---

docs/how-to-guides/how-to-run-chainhook-as-a-service-using-bitcoind.md
docs/how-to-guides/how-to-run-chainhook-as-a-service-using-stacks.md
examples/arkadiko-data-indexing/README.md

Updated commands to remove '$' prefix.
Fixes https://github.com/hirosystems/chainhook/issues/273

Removed $ prefix from all the commands

---

components/chainhook-cli/src/scan/stacks.rs
components/chainhook-sdk/src/chainhooks/stacks/mod.rs
components/chainhook-sdk/src/chainhooks/tests/mod.rs

Address https://github.com/hirosystems/chainhook/issues/354 and https://github.com/hirosystems/chainhook/issues/358
N/A

fix: asset-identifier filtering

---

docs/getting-started.md
docs/how-to-guides/how-to-run-chainhook-as-a-service-using-bitcoind.md
docs/how-to-guides/how-to-run-chainhook-as-a-service-using-stacks.md
docs/how-to-guides/how-to-use-chainhooks-with-bitcoin.md
docs/how-to-guides/how-to-use-chainhooks-with-stacks.md
docs/overview.md

- Updated titles for predicates definitions to use Chainhooks.

Updated titles to use chainhooks for predicates

---

docs/how-to-guides/how-to-use-chainhooks-with-stacks.md

Added an example to use the `between` operator.
None

Added an example to use the between operator

---

Cargo.lock
components/chainhook-cli/Cargo.toml
components/chainhook-sdk/Cargo.toml
components/chainhook-sdk/src/chainhooks/bitcoin/mod.rs
components/chainhook-sdk/src/observer/mod.rs

Couple of adjustments required for ordhook!

chore: tweak chainhook-sdk

---

components/chainhook-sdk/src/chainhooks/stacks/mod.rs
components/chainhook-sdk/src/chainhooks/tests/fixtures/stacks/testnet/occurrence.json

fix: add nonce to serialized stacks tx

---

components/chainhook-sdk/src/chainhooks/stacks/mod.rs

fix: add auth header for stacks hook

---

components/chainhook-sdk/src/indexer/bitcoin/mod.rs

In this PR, we're attempting to detect http / rpc errors as early as possible so we can leverage the loop / retry mechanism as early as possible in case of failure.

feat: detect http / rpc errors as early as possible

---

README.md

Updates the README with updated predicate examples. See #507

update README examples

---

components/chainhook-cli/src/cli/mod.rs
components/chainhook-cli/src/service/tests/mod.rs
components/chainhook-sdk/src/chainhooks/bitcoin/mod.rs
components/chainhook-sdk/src/chainhooks/bitcoin/tests.rs
components/chainhook-sdk/src/chainhooks/types.rs
components/chainhook-sdk/src/indexer/bitcoin/mod.rs
components/chainhook-sdk/src/indexer/tests/helpers/transactions.rs
components/chainhook-sdk/src/observer/tests/mod.rs
components/chainhook-types-rs/src/lib.rs
components/chainhook-types-rs/src/ordinals.rs
components/chainhook-types-rs/src/rosetta.rs
components/client/typescript/src/schemas/bitcoin/if_this.ts
components/client/typescript/src/schemas/bitcoin/payload.ts
docs/chainhook-openapi.json

feat: add brc-20 schemas for ordhook

---

Cargo.lock
Cargo.toml
components/chainhook-sdk/Cargo.toml
components/chainhook-sdk/src/chainhooks/types.rs
components/chainhook-sdk/src/indexer/mod.rs
components/chainhook-types-rs/Cargo.toml

- update pox config default setting to use 20 / 5 on devnet
- update dependencies from the clarinet repo
Note: I realized that we had an other PoxConfig struct somewhere else in the repo 👎 
Something I'd like to fix in a future PR

feat: update pox default settings

---

README.md
docs/how-to-guides/how-to-run-chainhook-as-a-service-using-stacks.md

Hello
I found several spelling issues in your docs.
Hope I was helpful.

Fix spelling issue
